project:
  type: website
  output-dir: docs

website:
  title: "Workflow Manual for Environmental Data Projects"
  repo-url: https://github.com/ascol25/Workflow-Manual_Environmental-Datasets
  repo-actions: [source, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: Workflow
        contents:
          - project-structure.qmd
          - git-workflow.qmd
          - renv.qmd
          - data-management.qmd
      - section: Support
        contents:
          - troubleshooting.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true